name: Check README

on: push

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.123.3/hugo_0.123.3_linux-amd64.deb
          sudo dpkg -i hugo_0.123.3_linux-amd64.deb
      - name: Config git
        run: |
          git config --global user.name "Auto Docs"
          git config --global user.email "auto-docs@mail.com"
          git submodule add  https://${{ secrets.TOKEN }}@github.com/CAMINHO-PARA/REPOSITORIO-DESTINO.git repositorio-destino

      - name: Check for README.md and img directory
        run: |
          if [ -f "./README.md" ]; then
            caminho_destino="Franzininho DIY Board"

            if git diff --quiet HEAD~1 HEAD "./README.md"; then
                  echo "No changes to README.md"
                  exit 0
            fi

            cd ./repositorio-destino/
            rm -rf "./content/$caminho_destino/" # remove the directory de dntro de repositorio-destino
            hugo new content "$caminho_destino/_index.md"
            cat "../README.md" >> "./content/$caminho_destino/_index.md"

            if [[ -d "../img" ]]; then
              pwd
              cp -r "../img" "./content/$caminho_destino/img"
              echo "copiando pasta imagens"
            else
              echo " does not have img folder"
            fi

            cd ..
          fi
          cd ./repositorio-destino/
          git add .
          git commit -m "Copied README.md files and img directories"
          git push  https://${{ secrets.TOKEN }}@github.com/CAMINHO-PARA/REPOSITORIO-DESTINO.git
